default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blogster
  username: root
  password: 

test:
  <<: *default
  database: blogster_test
  username: root
  password:

production:
  <<: *default
  database: db/production.sqlite3
